import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart'; // Added import

import '../../domain/entities/group.dart';
import '../providers/group_provider.dart';

class CreateGroupScreen extends StatefulWidget {
  const CreateGroupScreen({super.key});

  @override
  CreateGroupScreenState createState() => CreateGroupScreenState();
}

class CreateGroupScreenState extends State<CreateGroupScreen> {
  final _formKey = GlobalKey<FormState>();
  String _groupName = '';
  String _selectedAvatarUrl =
      'assets/images/group_project_phoenix.png'; // Default avatar

  final List<String> _avatarOptions = [
    'assets/images/group_project_phoenix.png',
    'assets/images/group_weekend_trip.png',
    'assets/images/group_design_team.png',
    'assets/images/globe.png',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Group'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            context.pop();
          },
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: const InputDecoration(labelText: 'Group Name'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a group name';
                  }
                  return null;
                },
                onSaved: (value) {
                  _groupName = value!;
                },
              ),
              const SizedBox(height: 20),
              DropdownButtonFormField<String>(
                initialValue: _selectedAvatarUrl,
                decoration: const InputDecoration(labelText: 'Group Avatar'),
                items: _avatarOptions.map((String url) {
                  return DropdownMenuItem<String>(
                    value: url,
                    child: Row(
                      children: [
                        CircleAvatar(
                          backgroundImage: AssetImage(url),
                          radius: 20,
                        ),
                        const SizedBox(width: 10),
                        Text(url.split('/').last), // Display file name
                      ],
                    ),
                  );
                }).toList(),
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedAvatarUrl = newValue!;
                  });
                },
              ),
              const SizedBox(height: 20),
              Consumer<GroupProvider>(
                builder: (context, groupProvider, child) {
                  return ElevatedButton(
                    onPressed: groupProvider.isLoading
                        ? null
                        : () async {
                            if (_formKey.currentState!.validate()) {
                              _formKey.currentState!.save();
                              final currentUser =
                                  Supabase.instance.client.auth.currentUser;
                              final newGroup = Group(
                                id: '', // Placeholder, ID will be generated by repository
                                name: _groupName,
                                avatarUrl:
                                    _selectedAvatarUrl, // Use selected avatar
                                memberIds: currentUser != null
                                    ? [currentUser.id]
                                    : [], // Include current user's ID
                                lastMessage: 'No messages yet',
                                time: DateTime.now(),
                              );
                              final navigator = Navigator.of(context);
                              final scaffoldMessenger = ScaffoldMessenger.of(
                                context,
                              );
                              await context.read<GroupProvider>().createGroup(
                                newGroup,
                              );
                              if (!mounted) return;
                              if (groupProvider.hasError) {
                                scaffoldMessenger.showSnackBar(
                                  SnackBar(
                                    content: Text(
                                      'Error creating group: ${groupProvider.errorMessage}',
                                    ),
                                  ),
                                );
                              } else {
                                navigator.pop();
                              }
                            }
                          },
                    child: groupProvider.isLoading
                        ? const CircularProgressIndicator()
                        : const Text('Create Group'),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
