// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/events/domain/usecases/create_event_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/core/error/failures.dart' as _i6;
import 'package:app/features/events/domain/entities/event.dart' as _i2;
import 'package:app/features/events/domain/entities/event_invitation.dart'
    as _i7;
import 'package:app/features/events/domain/repositories/event_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.Either<_i6.Failure, List<_i2.Event>>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue:
                _i4.Stream<_i5.Either<_i6.Failure, List<_i2.Event>>>.empty(),
          )
          as _i4.Stream<_i5.Either<_i6.Failure, List<_i2.Event>>>);

  @override
  _i4.Future<_i2.Event> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEvent, [id])),
            ),
          )
          as _i4.Future<_i2.Event>);

  @override
  _i4.Future<_i2.Event> createEvent(
    _i2.Event? event, {
    List<String>? inviteeIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [event], {#inviteeIds: inviteeIds}),
            returnValue: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(
                this,
                Invocation.method(
                  #createEvent,
                  [event],
                  {#inviteeIds: inviteeIds},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Event>);

  @override
  _i4.Future<void> updateEvent(_i2.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.EventInvitation>> getEventInvitations(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventInvitations, [eventId]),
            returnValue: _i4.Future<List<_i7.EventInvitation>>.value(
              <_i7.EventInvitation>[],
            ),
          )
          as _i4.Future<List<_i7.EventInvitation>>);

  @override
  _i4.Future<void> sendEventInvitations(
    String? eventId,
    List<String>? inviteeIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendEventInvitations, [eventId, inviteeIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> respondToInvitation(
    String? invitationId,
    _i7.InvitationStatus? status, {
    DateTime? suggestedDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #respondToInvitation,
              [invitationId, status],
              {#suggestedDate: suggestedDate},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.Either<_i6.Failure, List<_i7.EventInvitation>>>
  getMyInvitations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyInvitations, [userId]),
            returnValue:
                _i4.Stream<
                  _i5.Either<_i6.Failure, List<_i7.EventInvitation>>
                >.empty(),
          )
          as _i4.Stream<_i5.Either<_i6.Failure, List<_i7.EventInvitation>>>);
}
