// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/chats/domain/usecases/create_chat_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/core/error/failures.dart' as _i5;
import 'package:app/features/chats/domain/entities/chat.dart' as _i7;
import 'package:app/features/chats/domain/entities/chat_member.dart' as _i10;
import 'package:app/features/chats/domain/entities/chat_with_last_message.dart'
    as _i6;
import 'package:app/features/chats/domain/entities/message.dart' as _i8;
import 'package:app/features/chats/domain/entities/message_with_sender.dart'
    as _i9;
import 'package:app/features/chats/domain/repositories/chat_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.ChatWithLastMessage>>>
  getRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentChats, []),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.ChatWithLastMessage>>
                >.empty(),
          )
          as _i4.Stream<
            _i2.Either<_i5.Failure, List<_i6.ChatWithLastMessage>>
          >);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i7.Chat>>> getChats() =>
      (super.noSuchMethod(
            Invocation.method(#getChats, []),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, List<_i7.Chat>>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i7.Chat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>> getChat(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getChat, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>>.value(
              _FakeEither_0<_i5.Failure, _i7.Chat>(
                this,
                Invocation.method(#getChat, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>> createChat(
    String? name,
    List<String>? memberIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [name, memberIds]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>>.value(
              _FakeEither_0<_i5.Failure, _i7.Chat>(
                this,
                Invocation.method(#createChat, [name, memberIds]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Chat>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateChat(_i7.Chat? chat) =>
      (super.noSuchMethod(
            Invocation.method(#updateChat, [chat]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateChat, [chat]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteChat(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteChat, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i8.Message>>> getMessages(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, List<_i8.Message>>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i8.Message>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.MessageWithSender>>>
  getLatestMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestMessages, [chatId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i9.MessageWithSender>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i9.MessageWithSender>>(
                    this,
                    Invocation.method(#getLatestMessages, [chatId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.MessageWithSender>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendMessage(
    String? chatId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [chatId, content]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#sendMessage, [chatId, content]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.ChatMember>>> getChatMembers(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMembers, [chatId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i10.ChatMember>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i10.ChatMember>>(
                    this,
                    Invocation.method(#getChatMembers, [chatId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i10.ChatMember>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> addChatMember(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addChatMember, [chatId, userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#addChatMember, [chatId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> removeChatMember(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeChatMember, [chatId, userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#removeChatMember, [chatId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
